# This is a basic workflow to help you get started with Actions
name: publish

on: 
  release:
    types: # This configuration does not affect the page_build event above
      - created
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: nupkg
        path: nupkg
    
    - name: push package
      run: dotnet nuget push "nupkg/*.nupkg" -k ${{ NUGET_KEY }} -s https://api.nuget.org/v3/index.json
